- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resourcegroup_name: ansible-middleware-rg
    resourcegroup_location: eastus
    virtualnetwork_name: ansible-middleware-Vnet
    subnet_name: ansible-middleware-subnet
    vm_name: ansible-middleware-demo
    admin_username: azureuser 
    admin_password: Password12345
    location: eastus
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resourcegroup_name }}"
      location: "{{ resourcegroup_location }}"

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ virtualnetwork_name }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtualnetwork_name }}"
  
  - name: Create Network Security Group that allows HTTP
    azure_rm_securitygroup:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_name }}"
      rules:
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
  
  - name: Create public IP address for VM
    azure_rm_publicipaddress:
      resource_group: "{{ resourcegroup_name }}"
      allocation_method: Static
      name: "{{ vm_name }}"
    register: output_ip_address

  - name: Create virtual network interface card for VM
    azure_rm_networkinterface:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_name }}"
      virtual_network: "{{virtualnetwork_name}}"
      subnet:  "{{ subnet_name }}"
      public_ip_name: "{{ vm_name }}"
      security_group: "{{ vm_name }}"

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_name }}"
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      vm_size: Standard_DS1_v2
      network_interfaces: "{{ vm_name }}"
      image:
        offer: RHEL
        publisher: RedHat
        sku: 7-LVM
        version: latest