---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resourcegroup_name }}"
    location: "{{ resourcegroup_location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ virtualnetwork_name }}"
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ subnet_name }}"
    virtual_network: "{{ virtualnetwork_name }}"
    address_prefix: "10.0.1.0/24"

- name: Create Network Security Group that allows HTTP
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ securitygroup_name }}"
    rules:
    - name: HTTP
      protocol: TCP
      destination_port_range: " {{ port }}"
      access: Allow
      priority: "{{ priority }}"
      direction: Inbound
  when: port and priority not None

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    ssh_password_enabled: false
    ssh_public_keys:
    - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
      key_data: "{{ key_data }}"
    vm_size: " {{ vm_size }}"
    tags:
      site: "{{ site }}"
      role: "{{ role }}"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: latest

