---
- name: Remove a VM and all resources that were autocreated
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup_name }}"
    name: {{"vm_name"}}
    remove_on_absent: all_autocreated
    state: absent
