- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: azure_vm
      vars:
        action: create
        name: "{{ item.name }}"
        site: "{{ item.site }}"
        role: "{{ item.role }}"
        port:  "{{ item.port }} | default('None specified') }}"
        priority: "{{ item.priority }}  | default('None specified') }}"
      loop:
        - { name: 'loadbalancer0', site: 'site0', role: 'loadbalancer', port: 22, priority: 100}
